### ISSUE TITLE
typo in the install script `trasmuter` instead of `btc-transmuter`

### ISSUE THREAD

**Issue by JanCernyCZ** [taxmeifyoucan/cadr-docs#2]
https://github.com/taxmeifyoucan/cadr-docs/tree/master/usage/supported-software#applications

`apt install selfhost-dashboard thunderhub ridetheln btcpayserver transmuter electrs btc-rpc-explorer `
correct:
`apt install selfhost-dashboard thunderhub ridetheln btcpayserver btc-transmuter electrs btc-rpc-explorer`

**Comment by taxmeifyoucan** [comment]
Thanks for the report and prompt fix!
